### ISSUE TITLE
about THE NUM_CLASSES

### ISSUE THREAD

**Issue by irfanICMLL** [hellochick/ICNet-tensorflow#13]
The num_classes in the train.py equals 27.
But the cityscapes dataset has 19 classes in the trainIDs?
I feel a little confused about this...?

Did you train the model on cityscapes? or you load the pretrained model provided by the author?
Can I change the num_class to 19 and still ues the parameter you offered？

**Comment by hellochick** [comment]
@irfanICMLL , I have trained on ADE20k dataset and compressed the class numbers to 27, and you can see the result in the bottom of README, sorry for confusing you. 

For the Cityscapes, I converted the weight from the original author. You can still use the parameters I offered and change the number of classes to 19, but it's hard to reproduce the performance described in the paper because the author first trained on the other model then do model compression.

**Comment by irfanICMLL** [comment]
I got it~  There is a problem on my  browser. So I did not see your own results. Now I understand~Thxs~

**Comment by hellochick** [comment]
@irfanICMLL I replied in the other issue and make more detailed explanation~~~ XD
