### ISSUE TITLE
Error arises from the size of own training data

### ISSUE THREAD

**Issue by YiSyuanChen** [hellochick/ICNet-tensorflow#18]
Hello,
I tried to use own dataset to train the model, but it has some problems. The following are the steps I've done:

note: The dataset has 32 classes, and the image size is 360*480.

1. changed the "INPUT_SIZE" to 360*480 in train.py
2. changed the "NUM_CLASSES" to 32 in train.py
3. To use your pretrained model, I modified the name of "conv6_cls", "sub4_out" and "sub24_out" in class ICNet_BN, since they all related to num_classes. Then I set the "ignore_missing" to True in line 186 in train.py.
4. run the command "python train.py --update-mean-var --train-beta-gamma", but it show error "ValueError: Dimension 1 in both shapes must be equal, but are 44 and 45
        From merging shape 0 with other shapes. for 'sub12_sum' (op: 'AddN') with input shapes: [32,44,60,128], [32,45,60,128].
"
5. change the "INPUT_SIZE" back to 480*480 (though it does not make sense)
6. again run the command "python train.py --update-mean-var --train-beta-gamma" and it successfully start to train.
7. try to use the checkpoint just trained to do inference, so I run the command "python inference.py --img-path=./input/test.png --model=others", but it has error (as I expected).

It seems that your model can train different size of image, and you also have updated the code enabling to inference in different size. I am still figuring out the code. I try to clearly explain what I thought. Any comments will be much appreciated. Really thanks your help in advance.

**Comment by hellochick** [comment]
Hey @YiSyuanChen, sorry for confusing you. I have only updated the inference code enabling to fit every different size. For training code, you need to adjust the size to the multiple of 32 because the output stride of network is 32 ( that is, your feature is 32x smaller than input image ). Is the comment helpful for you? If you have any question, feel free to let me know.

**Comment by YiSyuanChen** [comment]
Thanks for your reply!! It's really helpful, and I'll keep trying. Thanks for your help again :)

**Comment by An-Pan** [comment]
@YiSyuanChen  Can you tell me some detail of modify the name "conv6_cls" , I want do detect on 12 classes, Thk.

**Comment by MikeyLev** [comment]
Hey  @YiSyuanChen, @hellochick I did the very same steps as YiSyuanChen, my images are 480x480 and I only changed the tf.image.decode_jpeg function to tf.image.decode_image, when I try to train I get the following error:
`Traceback (most recent call last):
  File "train.py", line 210, in <module>
    main()
  File "train.py", line 199, in main
    loss_value, loss1, loss2, loss3, _ = sess.run([reduced_loss, loss_sub4, loss_sub24, loss_sub124, train_op], feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 48, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

Caused by op u'create_inputs/batch', defined at:
  File "train.py", line 210, in <module>
    main()
  File "train.py", line 135, in main
    image_batch, label_batch = reader.dequeue(args.batch_size)
  File "/home/ubuntu/githubrepo/ICNET2/ICNet-tensorflow/image_reader.py", line 116, in dequeue
    num_elements)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 917, in batch
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 712, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1328, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 48, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
` 
Any clue?
Really thanks your help in advance.

**Comment by hellochick** [comment]
@MikeyLev, it seems that the number of images are not enough to fill the input queue. Can you check your dataset size?

**Comment by MikeyLev** [comment]
@hellochick Thanks, This was the problem although I must understand what this means...

**Comment by JuOllie** [comment]
@MikeyLev I'm getting the same error, can you tell me your data-set size. I have around 260 training images.
